version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto19
  build:
    commands:
      - export AWS_ACCESS_KEY_ID=AKIAWEVMQT5S5KUAGKUC
      - export AWS_SECRET_ACCESS_KEY=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
      - export AWS_REGION=us-east-1
      - export S3_BUCKET_NAME=msp-academy1
      - export S3_BASE_URL=https://msp-academy1.s3.amazonaws.com/
      - export DB_USERNAME=postgres
      - export DB_PASSWORD=MSP1234$
      - export SERVER_PORT=8080
      - export DATABASE=mspacademy
      - export EMAIL_USERNAME=mspacademy0@gmail.com
      - export EMAIL_PASSWORD="apcd jiia brgu gezs"
      - export FRONTEND_URL=54.173.110.235:3000
      - export DB_HOST=mspacademy.cun6qh72hxrl.us-east-1.rds.amazonaws.com
      
      - mvn clean install
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - target/*.jar
    - scripts/*.sh
    - appspec.yml
  discard-paths: yes
